schema = 3

[mod]
  [mod."cloud.google.com/go/compute"]
    version = "v1.20.1"
    hash = "sha256-HQvSLdoSagQsuqOb/D9+xMc8nE9Y44Z30rQgd2AGEr8="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.3"
    hash = "sha256-kYB1FTQRdTDqCqJzSU/jJYbVUGyxbkASUKbEs36FUyU="
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/akutz/memconn"]
    version = "v0.1.0"
    hash = "sha256-WOs/RQYjQbn41ui8ztHgWSd4jxydE+fvIrl/0dmHD9Y="
  [mod."github.com/alexbrainman/sspi"]
    version = "v0.0.0-20231016080023-1a75b4708caa"
    hash = "sha256-Joa/NfBofK7lRlknQ5LVYD4M/dpd9xaCqsvYUBhKW0I="
  [mod."github.com/anmitsu/go-shlex"]
    version = "v0.0.0-20200514113438-38f4b401e2be"
    hash = "sha256-L3Ak4X2z7WXq7vMKuiHCOJ29nlpajUQ08Sfb9T0yP54="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.24.1"
    hash = "sha256-qZDUrodVDWWtdQ6zYuNHxpXt2quK56pPoZsKdRGmYzk="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.26.5"
    hash = "sha256-RAXQlnUAsxgi2BndS+Uh2Cw+TCbtUx9BB0Tqqz50rLE="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.16.16"
    hash = "sha256-qjtE3/VxNAEtS68nLXULgjO+LO3EkayGkr2iU300xdA="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.14.11"
    hash = "sha256-j8LHZYM+rBmWHV1PT/H6lDL/3vgBqvQxoY2bVuOi7zo="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.2.10"
    hash = "sha256-fhrws72g+ecgXnkiip0GQ206XfVdxDA7/Rz9X3nvgd8="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.5.10"
    hash = "sha256-Rbj+matn96a/3Nj8EpLgrTycSV+331+WWJd5Lpk1LlQ="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.7.2"
    hash = "sha256-6ev22rRSz4TuoX1AoCDr67qA15kg+cHMuQeTXwp8AFg="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.10.4"
    hash = "sha256-Wvbil3pNKlCyn0SWNXCobxzJGeE+2Eb7GNP2OZATTfY="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.10.10"
    hash = "sha256-vUSnrZzo3mzfZsthjjZRmGNrXkQ4D2B7Glzu66N5MrQ="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssm"]
    version = "v1.44.7"
    hash = "sha256-U7XGN5O0Ksp6O3a2Nkb0WinTwuIHjCw5UNSwPjrMo8k="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.18.7"
    hash = "sha256-+1q43+9Cx/K3/T+LJJLV1h2PLHsG/YKHUSgwC5r3uNQ="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.21.7"
    hash = "sha256-aoolSWOU3Sb3weV2yf2wACuh3fYaUmyGXCZ2dTvcg4A="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.26.7"
    hash = "sha256-0LGfjSa65wNKuV/TH66XfN/uF4lZF9bSszbfTFWcLjY="
  [mod."github.com/aws/smithy-go"]
    version = "v1.19.0"
    hash = "sha256-KsQMOHJFIXRF+8c4WxiXA/u1Ok6hEF6eylvnfdRGivg="
  [mod."github.com/bits-and-blooms/bitset"]
    version = "v1.13.0"
    hash = "sha256-1jccFEH9In72Jt3wSn4vi4/MJd/UDfDrC9DlmsGVc9o="
  [mod."github.com/coder/websocket"]
    version = "v1.8.12"
    hash = "sha256-jEaJSKcwmKtXFkvtxwpEdFMdazXZM6bY2u5TGBimklI="
  [mod."github.com/containerd/log"]
    version = "v0.1.0"
    hash = "sha256-vuE6Mie2gSxiN3jTKTZovjcbdBd1YEExb7IBe3GM+9s="
  [mod."github.com/containerd/stargz-snapshotter/estargz"]
    version = "v0.15.1"
    hash = "sha256-yVwNWyOd7/Ov+GBNyOIEPpGGtTq8KOWsnp2z4pU00Bs="
  [mod."github.com/coreos/go-iptables"]
    version = "v0.7.1-0.20240112124308-65c67c9f46e6"
    hash = "sha256-kjnry8ld5Keew5q+tX7GSdGVZaXlehs2Lt+z8Rokhns="
  [mod."github.com/creack/pty"]
    version = "v1.1.23"
    hash = "sha256-42k7lObS5h99pPoicb6tkRlBvVvSPqsy+aC87PWq2o4="
  [mod."github.com/dblohm7/wingoes"]
    version = "v0.0.0-20240119213807-a09d6be7affa"
    hash = "sha256-zUj7jSZQiX53+4OyRq7LaQXp8nx8+JRpyT6IFdktyw0="
  [mod."github.com/digitalocean/go-smbios"]
    version = "v0.0.0-20180907143718-390a4f403a8e"
    hash = "sha256-Hgx1ML3rigdYXx5ntnEYD5JEk6kJv1cL0+/GDbnPkbo="
  [mod."github.com/distribution/reference"]
    version = "v0.6.0"
    hash = "sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4="
  [mod."github.com/docker/cli"]
    version = "v25.0.0+incompatible"
    hash = "sha256-VKSQYE0OKk+MLBMmCcqM+VDUMYic2YQ24ECst7iqlxM="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker"]
    version = "v27.2.1+incompatible"
    hash = "sha256-iHbWQ7NJRh0qfu5Bi1K9HdZUzGq3UI9B12yZyZC1XKM="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.8.1"
    hash = "sha256-mBp/8jYhfZ2s5GuWkMVUmncCjCynfD5KZzIt9qymb9E="
  [mod."github.com/docker/go-connections"]
    version = "v0.4.0"
    hash = "sha256-GHNIjOuuNp5lFQ308+nDNwQPGESCVV7bCUxSW5ZxZlc="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/evanw/esbuild"]
    version = "v0.23.1"
    hash = "sha256-wK8lHEzyZvrNGBeYfxGhlzvbvGvSpgNbefZaW6rHn40="
  [mod."github.com/fatih/color"]
    version = "v1.17.0"
    hash = "sha256-QsKMy3MsvjbYNcA9jP8w6c3wpmWDZ0079bybAEzmXR0="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.6.0"
    hash = "sha256-8EMjmc2FYVb0OXuzU1FWkSqYEtJjYdIT2PWsChoiTyQ="
  [mod."github.com/gaissmai/bart"]
    version = "v0.11.1"
    hash = "sha256-Z9rSmZbNRUpcIHVRVW8XFB4qDj57bvK/CwzQWaevy+Y="
  [mod."github.com/go-json-experiment/json"]
    version = "v0.0.0-20231102232822-2e55bd4e08b0"
    hash = "sha256-ltOLec3r0dGA/k1TTrQjuMuHxdxBlALkfLbdKuUNvmg="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.1-0.20230522191255-76236955d466"
    hash = "sha256-OdcyeoGQ4xWUpl21WKXkbAm8yZHMDp8giY02arupjb4="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/google/btree"]
    version = "v1.1.2"
    hash = "sha256-K7V2obq3pLM71Mg0vhhHtZ+gtaubwXPQx3xcIyZDCjM="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/nftables"]
    version = "v0.2.1-0.20240414091927-5e242ec57806"
    hash = "sha256-OXMzx4Exf++E4UzCUE1gw3TOrfyI187cFu3cDZ9ifKU="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/csrf"]
    version = "v1.7.2"
    hash = "sha256-pzOWbw8AOjhdRJYKlPBfh1j9a8TGNxgrlS4AmZpE1s8="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.2"
    hash = "sha256-KeMHNM9emxX+N0WYiZsTii7n8sNsmjWwbnQ9SaJfTKE="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/hdevalence/ed25519consensus"]
    version = "v0.2.0"
    hash = "sha256-KTbeKMOT/HCJjDHqyciQjJPPgpNk6H0VyQCCbeGgs7Y="
  [mod."github.com/hugomd/ascii-live"]
    version = "v0.0.0-20231008062449-0e53a4799f1e"
    hash = "sha256-0o+LuqyOscBKUr7fZXSF9UZoC/3Y4Q7DVZU9cZM4GgU="
  [mod."github.com/illarion/gonotify"]
    version = "v1.0.1"
    hash = "sha256-73KDUfk5iNo12u+nNN2H4UTfJ1FlLifahnFNPzV1P/k="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/insomniacslk/dhcp"]
    version = "v0.0.0-20231206064809-8c70d406f6d2"
    hash = "sha256-PHiso7HGNjCGbGdZ7TMGnSGzPDUTpvWpqAccoKPAaWM="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/josharian/native"]
    version = "v1.1.1-0.20230202152459-5c7d0dd6ab86"
    hash = "sha256-dgyrLXuM55z8FAoUjyt5TDlzim6HfphWo5wx1/DHLwE="
  [mod."github.com/jsimonetti/rtnetlink"]
    version = "v1.4.0"
    hash = "sha256-GnrF2yxgm/h1JSTN1PwI4ysTl+oY0AyWzf3Ni7LZqRM="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.4"
    hash = "sha256-5E7dDtDKfL3jy7zJxHBMV57WlHZrP/OoEX5e6cOPba0="
  [mod."github.com/kortschak/wol"]
    version = "v0.0.0-20200729010619-da482cc4850a"
    hash = "sha256-lnr9r/KNv4EeeNohFImC3Vd5E9nJ0N+4ZZ0VHFjwHps="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mdlayher/genetlink"]
    version = "v1.3.2"
    hash = "sha256-pgwXkyDY1dlB8tmV1lQ0Bz/2g0zmJOyXvQjacACy924="
  [mod."github.com/mdlayher/netlink"]
    version = "v1.7.2"
    hash = "sha256-08qlkKvG1+XFY3MDx7M1jdvaDMsmF9qv5/xMNaw3snc="
  [mod."github.com/mdlayher/sdnotify"]
    version = "v1.0.0"
    hash = "sha256-O7MJt6Bam2bUoede07Z1T6EtW+kCJ+/4dJtYopZct1s="
  [mod."github.com/mdlayher/socket"]
    version = "v0.5.0"
    hash = "sha256-3zEbix66G+LQ2xAQW9XmkyubK9R+Vwnm09H5fqqLC7w="
  [mod."github.com/miekg/dns"]
    version = "v1.1.58"
    hash = "sha256-UGvyC1Abh2S5VaAUCV9AUuDMrCvpiWQy/UnYM9DfIB8="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/moby/docker-image-spec"]
    version = "v1.3.1"
    hash = "sha256-xwSNLmMagzywdGJIuhrWl1r7cIWBYCOMNYbuDDT6Jhs="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0-rc6"
    hash = "sha256-D52gK6sMe/wM9jh5bqdtM1LgQlIDvjybNUbPbByBtyQ="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.21"
    hash = "sha256-u47Lm4tN2ChGDLGyR+Jpi/Mi0bOFBVT6PTpPFdu2rMU="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/sftp"]
    version = "v1.13.6"
    hash = "sha256-x1dTv4M1hRc0wsbTe4wOCM8jdH/GWzI8ls5lm92nZVg="
  [mod."github.com/prometheus-community/pro-bing"]
    version = "v0.4.0"
    hash = "sha256-3TH0wB85OITw3uzTcEva2EcEF6jNf98sAoSOsnL2G9g="
  [mod."github.com/safchain/ethtool"]
    version = "v0.3.0"
    hash = "sha256-q5bQGHB7cyEejA9tQkrhpvzpfYRvXcmClbWBgfs3Ymc="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/tailscale/certstore"]
    version = "v0.1.1-0.20231202035212-d3fa0460f47e"
    hash = "sha256-Q0HLTQPRsIizRqvdBBaLGoLascQiSpQm+X3NW3ytpDQ="
  [mod."github.com/tailscale/go-winio"]
    version = "v0.0.0-20231025203758-c4f33415bf55"
    hash = "sha256-WFW20c02gIk2MhafeVVNydmSfszPZegshDd2Y5abGgY="
  [mod."github.com/tailscale/golang-x-crypto"]
    version = "v0.0.0-20240604161659-3fde5e568aa4"
    hash = "sha256-vIrSd0emexe1lcjJqLbEtg7/TaZDnpGrDs96mxjANyE="
  [mod."github.com/tailscale/goupnp"]
    version = "v1.0.1-0.20210804011211-c64d0f06ea05"
    hash = "sha256-PRMJcYY+wjpbHkC9dQWTPErh2ID29UnFxehxmYR704I="
  [mod."github.com/tailscale/hujson"]
    version = "v0.0.0-20221223112325-20486734a56a"
    hash = "sha256-q9c2IjwbL0IgYPznVpQP1XT/8lrzH1niI3E+wjNcf5Y="
  [mod."github.com/tailscale/netlink"]
    version = "v1.1.1-0.20211101221916-cabfb018fe85"
    hash = "sha256-bMK5qqObMcxIbPy5XhOZP8TGDaXvDAHsE0FR68VMLi8="
  [mod."github.com/tailscale/peercred"]
    version = "v0.0.0-20240214030740-b535050b2aa4"
    hash = "sha256-82cdwvTUr47qMP2MHiMdY5O8vr/hA2aJ/KW2VTu97KI="
  [mod."github.com/tailscale/web-client-prebuilt"]
    version = "v0.0.0-20240226180453-5db17b287bf1"
    hash = "sha256-iE8PCr0At4P75cG7dDa6fwhARJUIUw9pwvgtQNMOjAA="
  [mod."github.com/tailscale/wireguard-go"]
    version = "v0.0.0-20240731203015-71393c576b98"
    hash = "sha256-AwaqXLIKa9TtyZJbAYwojPRC4p9NWxhk2GdQp/z6Khc="
  [mod."github.com/tcnksm/go-httpstat"]
    version = "v0.2.0"
    hash = "sha256-bCWn8E+DcZY6+yPu07AF3hCcDZx3CFdD74qfpDIgVqI="
  [mod."github.com/u-root/uio"]
    version = "v0.0.0-20240118234441-a3c409a6018e"
    hash = "sha256-rUjQMG+HprbgHKzrIPFrQ6S3BCEyYQyUbA/D72mY8iU="
  [mod."github.com/vbatts/tar-split"]
    version = "v0.11.5"
    hash = "sha256-kVD5X4eDO5fcLSUgWJcaa1iVBMcwjLpyb5KMKBuovcY="
  [mod."github.com/vishvananda/netlink"]
    version = "v1.2.1-beta.2"
    hash = "sha256-ePReedgYT0KuAx/HOUgG76zDZ2XpW/u8bGlsWysxKzE="
  [mod."github.com/vishvananda/netns"]
    version = "v0.0.4"
    hash = "sha256-tEba2cxyk3GdCYvEIttQ8aZCzHcB0ZiUt6fUEARDkWU="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.47.0"
    hash = "sha256-Pv1X0oIWYXyVxEaDQmgYcw+49I9+65N9Y+1wbxoXOog="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.30.0"
    hash = "sha256-2r706a1+LqhT3DNqVZB6NIVaBoPnQ257BJY8UQqtaSM="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.30.0"
    hash = "sha256-zQILxmK0vlE28y0KeM5LQYEZWrSfn8jrZ0Mg6M6arf8="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.30.0"
    hash = "sha256-mSfy2A7cxIjAOs9tZ74kgVnsnGZoC3be/MjjFlO8KCw="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.30.0"
    hash = "sha256-a+oojnlDDHnliphPvObLdW2jZjfSDcBF7QkV7H9ZltY="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.30.0"
    hash = "sha256-6YukUeYtMo5jtKsoQQwuy3Zyx1Cl2LRMONnF91PCBIk="
  [mod."go4.org/mem"]
    version = "v0.0.0-20220726221520-4f986261bf13"
    hash = "sha256-H2Fsuvzbqp/6JKzC03XPTQTSQBcGs+B5VGsBjrQDY3c="
  [mod."go4.org/netipx"]
    version = "v0.0.0-20231129151722-fdeea329fbba"
    hash = "sha256-qFrVlacz5R3Lpkzqeg1/1MYew3DJzY9hG0Uh/ua+SOU="
  [mod."golang.org/x/crypto"]
    version = "v0.27.0"
    hash = "sha256-8HP4+gr4DbXI22GhdgZmCWr1ijtI9HNLsTcE0kltY9o="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240119083558-1b970713d09a"
    hash = "sha256-JQ3JLywTjgboNhs12blhOkS3ty7m8sUa/zaWv1k/X28="
  [mod."golang.org/x/mod"]
    version = "v0.19.0"
    hash = "sha256-9TUzg1aDvdZw3Z8IyGGSVSnLfUwgeGC/vrnkhkarXL4="
  [mod."golang.org/x/net"]
    version = "v0.29.0"
    hash = "sha256-dH9Rdf5T04KJ4B5WvIZh12ogMbADWiWgIt77nvPTk2k="
  [mod."golang.org/x/oauth2"]
    version = "v0.16.0"
    hash = "sha256-fJfS9dKaq82WaYSVWHMnxNLWH8+L4aip/C1AfJi4FFI="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.25.0"
    hash = "sha256-PXZ9EQZ7SFpcL7d3E1+KGTxziYlHEIZPfoXEbnaVD3I="
  [mod."golang.org/x/term"]
    version = "v0.24.0"
    hash = "sha256-PfC5psjzEWKRm1DlnBXX0ntw9OskJFrq1RRjyBa1lOk="
  [mod."golang.org/x/text"]
    version = "v0.18.0"
    hash = "sha256-aNvJW4gQs+MTfdz6DZqyyHQS2GJ9W8L8qKPVODPn4+k="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."golang.org/x/tools"]
    version = "v0.23.0"
    hash = "sha256-z+9n75A3H4YtF+m60qwOXnmrVFtOvXsKQmc+i7Mb6q0="
  [mod."golang.zx2c4.com/wintun"]
    version = "v0.0.0-20230126152724-0fa3db229ce2"
    hash = "sha256-cjMLNjKnnupVROWmeASORVieAL9ieYdzX3cFzG8bCpo="
  [mod."golang.zx2c4.com/wireguard/windows"]
    version = "v0.5.3"
    hash = "sha256-wcJWS/4Fqbc+1RHSntex0zBdlHiZfzrea4QabYkNKvU="
  [mod."google.golang.org/appengine"]
    version = "v1.6.8"
    hash = "sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gvisor.dev/gvisor"]
    version = "v0.0.0-20240722211153-64c016c92987"
    hash = "sha256-7cE5aVAN6o+9GB7NJeAexSGAe0CkgcBADIWWHQhsSCU="
  [mod."tailscale.com"]
    version = "v1.72.1"
    hash = "sha256-zQMclvfOb47baKGLx6O3k1QGUeKsfVroIoA6+X1VksQ="
